name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    # Runs everyday at 1:00 AM
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"  # 更稳定版本

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator

      - name: Download BPB worker script
        run: |
          wget -O functions/_worker.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      - name: Obfuscate worker script (lightweight)
        run: |
          javascript-obfuscator functions/_worker.js --output functions/_worker.js \
            --compact true \
            --self-defending true \
            --rename-globals false \
            --string-array false \
            --control-flow-flattening false \
            --dead-code-injection false

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':obfuscation: update and optimize worker script'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
